import type { Character } from "../../types";

export const characters: Array<Character> = [
    "yu",
    "ayumu",
    "kasumi",
    "shizuku",
    "karin",
    "ai",
    "kanata",
    "setsuna",
    "emma",
    "rina",
    "shioriko",
    "mia",
    "lanzhu",
    "nana",
    "dark-shizuku",
    "club-president",
    "hanpen",
    "iroha",
    "kyoko",
    "asagi",
    "haruka",
    "christina",
    "kasane",
    "himeno",
    "misaki",
    "vice-president",
    "secretary",
    "other",
];
